### PR TITLE
Remove GPU compute capability from ACC target in build

### PR DESCRIPTION
**Pull request by christopherwharrop-noaa**
The compute capability setting in the `OpenACC_ACCEL_TARGET` is not portable across different GPU hardware/drivers.  Tests also show that it does not appear to impact performance.  This PR removes this flag to make the build system more portable without adding additional complexity.  Performance was measured with and without this flag on a V100 AWS p3.2xlarge instance as well as the P100 node on the NOAA FGE machine.  All tests showed no performance impact of removing this flag.

### CODE REVIEW

**Comment by dshawul** [comment]
Actually there is performance difference although not much for this particular kernel.
I made 10 runs with and without cc70 on V100 and computed the min and average times

With cc70

```
 Finished executing kernel in =   0.8731100    
 Finished executing kernel in =    1.055310    
 Finished executing kernel in =   0.7588580    
 Finished executing kernel in =   0.8268210    
 Finished executing kernel in =   0.7727070    
 Finished executing kernel in =   0.7411180    
 Finished executing kernel in =   0.8143380    
 Finished executing kernel in =   0.8521880    
 Finished executing kernel in =   0.8136350    
 Finished executing kernel in =   0.7928130 
```
`Min=0.7411180 Avg=0.8300898`

Without

```
 Finished executing kernel in =    1.068027    
 Finished executing kernel in =   0.8059900    
 Finished executing kernel in =   0.8668910    
 Finished executing kernel in =   0.8603370    
 Finished executing kernel in =   0.8956520    
 Finished executing kernel in =   0.7654550    
 Finished executing kernel in =   0.8809870    
 Finished executing kernel in =   0.8144780    
 Finished executing kernel in =   0.8222270    
 Finished executing kernel in =   0.8121610 
```
`Min=0.765455  Avg=0.8592205`

It does make things more comfortable for Cmake though. Executing a binary to figure out compute capability looks ugly.

**Comment by danielabdi-noaa** [comment]
Actually there is performance difference although not much for this particular kernel.
I made 10 runs with and without cc70 on V100 and computed the min and average times

With cc70

```
 Finished executing kernel in =   0.8731100    
 Finished executing kernel in =    1.055310    
 Finished executing kernel in =   0.7588580    
 Finished executing kernel in =   0.8268210    
 Finished executing kernel in =   0.7727070    
 Finished executing kernel in =   0.7411180    
 Finished executing kernel in =   0.8143380    
 Finished executing kernel in =   0.8521880    
 Finished executing kernel in =   0.8136350    
 Finished executing kernel in =   0.7928130 
```
`Min=0.7411180 Avg=0.8300898`

Without

```
 Finished executing kernel in =    1.068027    
 Finished executing kernel in =   0.8059900    
 Finished executing kernel in =   0.8668910    
 Finished executing kernel in =   0.8603370    
 Finished executing kernel in =   0.8956520    
 Finished executing kernel in =   0.7654550    
 Finished executing kernel in =   0.8809870    
 Finished executing kernel in =   0.8144780    
 Finished executing kernel in =   0.8222270    
 Finished executing kernel in =   0.8121610 
```
`Min=0.765455  Avg=0.8592205`

It does make things more comfortable for Cmake though. Executing a binary to figure out compute capability looks ugly.

**Review by danielabdi-noaa — DISMISSED** [review]

**Comment by christopherwharrop-noaa** [comment]
@danielabdi-noaa - Your performance tests were more robust than mine.  When I tested, I saw overlap in the range of timings between the two, and figured the difference was in the noise of the variations in runtime.  Maybe not.  I see you approved.  Do you think the performance impact is worth spending time trying to augment the build system with detection of compute capability?  For testing purposes, it surely doesn't matter. But we do want the build to be performant.

**Comment by christopherwharrop-noaa** [comment]
Ok, I think I have found a way to set compute capability automatically.  It's a big ugly, but not too horrible.

```
  include(FindCUDA/select_compute_arch)
  CUDA_DETECT_INSTALLED_GPUS(INSTALLED_GPU_CCS_1)
  string(STRIP "${INSTALLED_GPU_CCS_1}" INSTALLED_GPU_CCS_2)
  string(REPLACE " " ";" INSTALLED_GPU_CCS_3 "${INSTALLED_GPU_CCS_2}")
  string(REPLACE "." "" CUDA_ARCH_LIST "${INSTALLED_GPU_CCS_3}")
  SET(CMAKE_CUDA_ARCHITECTURES ${CUDA_ARCH_LIST})
```

And

```
  target_compile_options(crtm_kernel_gpu_v1 PUBLIC ${OpenACC_Fortran_OPTIONS}:cc${CUDA_ARCH_LIST},cuda${CUDAToolkit_VERSION_MAJOR}.${CUDAToolkit_VERSION_MINOR})
  target_compile_options(crtm_kernel_gpu_v2 PUBLIC ${OpenACC_Fortran_OPTIONS}:cc${CUDA_ARCH_LIST},cuda${CUDAToolkit_VERSION_MAJOR}.${CUDAToolkit_VERSION_MINOR})
```

The only bad thing is that it uses stuff from deprecated FindCUDA module.  However, doing this is an open issue in the CMake development.  See [this](https://stackoverflow.com/questions/68223398/how-can-i-get-cmake-to-automatically-detect-the-value-for-cuda-architectures) and [this](https://gitlab.kitware.com/cmake/cmake/-/issues/22375).  Given that full CMake support for this isn't likely coming soon, I think we should use the above workaround and fix it once there is a proper solution (we can't wait for cmake development to figure this out).

**Comment by dshawul** [comment]
Yes, that sounds good.
Btw does it compile with cmake 3.10.2 ? It is not able to find OpenACC package on the nvidia system for some reason

```
-- Found OpenMP: TRUE (found version "4.5") found components:  C Fortran 
-- Found OpenACC_C: -fopenacc  (found version "2.0") 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenACC_Fortran (missing: OpenACC_Fortran_FLAGS) (found
  version "1.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenACC.cmake:247 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/u00uaoq7lvwRScc7u4357/SENA-crtm/ref/build/CMakeFiles/CMakeOutput.log".
```

**Comment by christopherwharrop-noaa** [comment]
@danielabdi-noaa - I think cmake 3.10 is too old.  I've modified the config to require a newer version.  Status checks may fail if that version is not installed on github runners.

**Review by danielabdi-noaa — APPROVED** [review]

**Pull request merged**
